// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Backdrop } from "../theme.slint";

// Generic page component
export component GenericPage inherits Rectangle
{
    padding: 0px;

    in-out property icon-source <=> img.source;
    in-out property title <=> title.text;
    in-out property subtitle <=> subtitle.text;

    HorizontalBox {
        alignment: start;
        spacing: 96px;
        padding: 0px;
        padding-left: 96px;

        VerticalBox {
            alignment: center;
            padding: 0px;
            img := Image {
                width: 256px;
                padding-right: 96px;
            }
        }

        VerticalBox {
            alignment: center;
            spacing: 16px;
            padding: 0px;
            title := Text {
                font-size: 24px;
                color <=> Backdrop.foreground;
            }

            subtitle := Text {
                font-size: 16px;
                color: Backdrop.foreground.with-alpha(0.8);
            }

            @children
        }
    }
}
