// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { ClientWindow } from "../components/index.slint";
import { SplashView } from "splash.slint";
import { LocalePage } from "locale.slint";
import { HorizontalBox, Palette, Button } from "std-widgets.slint";

import { Backdrop } from "../theme.slint";
import { DiskPage } from "disks.slint";
import { PageContainer } from "../components/page/index.slint";

// Main application window
export component MainWindow inherits Window
{
    title: "Installer";
    no-frame: true;
    background: transparent;

    preferred-width: 1024px;
    preferred-height: 768px;
    min-width: 1024px;
    min-height: 768px;

    callback request_close <=> window.request_close;
    callback request_minimize <=> window.request_minimize;
    callback request_toggle_maximize <=> window.request_toggle_maximize;
    callback drag_begin <=> window.drag_begin;

    in property<bool> is_maximized: false;

    in-out property<int> active_page: 0;
    out property<bool> can-go-back: active_page > 1;
    out property<bool> can-go-next: true;

    window := ClientWindow {
        backdrop-color: Backdrop.setup;
        maximized: root.is_maximized;

        pages := PageContainer {
            active_page <=> root.active_page;
            width: parent.width - 24px;
            height: parent.height;

            SplashView {
                width: parent.width;
                height: parent.height;
                install() => {
                    active_page = 1;
                }
            }

            LocalePage {
                width: parent.width;
                height: parent.height;
                can-go-back <=> root.can-go-back;
                can-go-next <=> root.can-go-next;
                on-next => { pages.go_next(); }
                on-back => { pages.go_back(); }
            }

            DiskPage {
                width: parent.width;
                height: parent.height;
                can-go-back <=> root.can-go-back;
                can-go-next: root.can-go-next;
                on-next => { pages.go_next(); }
                on-back => { pages.go_back(); }
            }
        }
    }
}
