// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { ClientWindow } from "../components/index.slint";

// Main application window
export component MainWindow inherits ClientWindow
{
    title: "Installer";
    backdrop-color: @linear-gradient(135deg, #2c3e50 0%, #3498db 50%, #2ecc71 100%);

    preferred-width: 1024px;
    preferred-height: 768px;
    min-width: 800px;
    min-height: 600px;
}
