// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox, Palette } from "std-widgets.slint";

// Window control button widget
export component WindowButton inherits Rectangle {
    in-out property<image> icon <=> img.source;
    callback clicked <=> touch.clicked;

    width: 24px;
    height: 24px;
    border-radius: 24px;
    background: touch.has-hover ? Palette.foreground.with-alpha(0.1) : transparent;


    animate background {
        duration: 250ms;
    }

    img := Image {
        source: @image-url("../../images/adwaita/window-minimize-symbolic.svg");
        colorize: white.with-alpha(0.8);
    }

    touch := TouchArea {
        mouse-cursor: MouseCursor.pointer;
    }
}

// Styled window controls for the titlebar
export component WindowControls {
    callback request_minimize <=> min.clicked;
    callback request_close <=> close.clicked;
    callback request_toggle_maximize <=> max.clicked;

    in property<bool> maximized;

    // Rounded corner on titlebar controls clipped to draw area of titlebar
    Rectangle {
        clip: true;

        // super sized rounded corner
        Rectangle {
            background: @linear-gradient(180deg, black.with-alpha(0.6) 0%, black.with-alpha(0.4) 100%);
            border-radius: 12px;
            width: parent.width * 2;
            height: parent.height * 2;
            x: 0px;
            y: 0px - box.height;
            border-color: black.with-alpha(0.05);
            border-width: 1px;
        }
    }

    height: 36px;
    padding: 0px;

    // Window control buttons
    box := HorizontalBox {
        spacing: 8px;
        alignment: stretch;
        width: parent.width;
        padding-left: 12px;
        padding-right: 12px;
        padding-top: 6px;

        min := WindowButton {
            icon: @image-url("../../images/adwaita/window-minimize-symbolic.svg");
        }

        max := WindowButton {
            icon: maximized ? @image-url("../../images/adwaita/window-restore-symbolic.svg") : @image-url("../../images/adwaita/window-maximize-symbolic.svg");
        }

        close := WindowButton {
            icon: @image-url("../../images/adwaita/window-close-symbolic.svg");
        }
    }
}
