// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox } from "std-widgets.slint";
import { WindowControls } from "controls.slint";

// A transparent titlebar to be rendered atop a themed window
// The window controls are in a styled section
export component Titlebar {
    padding: 0px;
    callback drag_begin();
    callback request_minimize <=> controls.request_minimize;
    callback request_close <=> controls.request_close;
    callback request_toggle_maximize <=> controls.request_toggle_maximize;
    in property<bool> maximized;

    rta := TouchArea {
        pointer-event(event) => {
            if (self.pressed && self.enabled && event.kind == PointerEventKind.move) {
                drag_begin();
            }
        }

        rect := Rectangle {
            width: parent.width;
            padding: 0px;
            height: 32px;
            background: transparent;

            HorizontalBox {
                alignment: end;
                spacing: 8px;
                padding: 0px;
                width: parent.width;
                height: parent.height;

                controls := WindowControls {
                    maximized: root.maximized;
                }
            }
        }
    }
}
