// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox } from "std-widgets.slint";
import { WindowControls } from "controls.slint";

// A transparent titlebar to be rendered atop a themed window
// The window controls are in a styled section
export component Titlebar {
    padding: 0px;
    callback drag_begin();
    callback request_minimize();
    callback request_close();

    rta := TouchArea {
        moved() => {
            if (rta.pressed && self.enabled) {
                drag_begin();
            }
        }

        Rectangle {
            width: parent.width;
            padding: 0px;
            height: 32px;
            background: transparent;

            HorizontalBox {
                alignment: end;
                spacing: 8px;
                padding: 0px;
                width: parent.width;
                height: parent.height;

                WindowControls {}
            }
        }
    }
}
