import { Titlebar } from "titlebar.slint";
import { DropShadow } from "dropshadow.slint";
import { ContentView } from "contentview.slint";

// Client-side decorated window
export component ClientWindow inherits Window
{
    padding: 0px;
    no-frame: true;
    background: transparent;

    in-out property <brush> backdrop-color: white.with-alpha(0.9);
    in-out property <brush> backdrop-border-color: black.with-alpha(0.1);

    DropShadow {
        width: parent.width - 6px;
        height: parent.height - 6px;
    }
    ContentView {
        backdrop-color: root.backdrop-color;
        backdrop-border-color: root.backdrop-border-color;
        width: parent.width - 12px;
        height: parent.height - 12px;

        Titlebar {
            width: parent.width;
            height: 32px;
        }
        @children
    }
}
