// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";
import { Backdrop } from "../../theme.slint";

// Generic page component
export component GenericPage inherits Rectangle
{
    padding: 0px;

    in-out property icon-source <=> img.source;
    in-out property title <=> title.text;
    in-out property subtitle <=> subtitle.text;
    in-out property can-go-back <=> back_button.visible;
    in-out property can-go-next <=> next_button.visible;

    callback on-back <=> back_button.clicked;
    callback on-next <=> next_button.clicked;

    HorizontalBox {
        alignment: start;
        spacing: 96px;
        padding: 0px;
        padding-left: 96px;

        VerticalBox {
            alignment: start;
            padding: 0px;
            padding-top: 96px;
            img := Image {
                width: 256px;
                padding-right: 96px;
            }
        }

        VerticalBox {
            alignment: space-around;
            spacing: 16px;
            padding: 0px;

            VerticalBox {
                alignment: stretch;
                title := Text {
                    font-size: 24px;
                    color <=> Backdrop.foreground;
                }

                subtitle := Text {
                    font-size: 16px;
                    color: Backdrop.foreground.with-alpha(0.8);
                }

                @children
            }

            HorizontalBox {
                alignment: end;
                padding: 0px;
                spacing: 12px;
                back_button := Button {
                    text: "Back";
                }
                next_button := Button {
                    text: "Next";
                    primary: true;
                }
            }
        }

    }
}
