// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { Palette } from "std-widgets.slint";

// The backdrop is a full screen overlay that is used to dim the background
export global Backdrop
{
    // Used for setup screens
    in-out property<brush> setup: Palette.color-scheme == ColorScheme.dark ?
        @linear-gradient(135deg, #1a1a1a 0%, #2c3e50 50%, #2c2c2c 100%) :
        @linear-gradient(135deg, #2c3e50 0%, #3498db 50%, #2ecc71 100%);

        // Backdrop's foreground:s some kinda white.
        in-out property<brush> foreground: Palette.color-scheme == ColorScheme.dark ?
            Colors.whitesmoke :
            Palette.selection-foreground;
}
