// SPDX-FileCopyrightText: Copyright © 2025 Serpent OS Developers
//
// SPDX-License-Identifier: MPL-2.0

import { IconTextItem } from "../../model/index.slint";
import { Palette } from "std-widgets.slint";
import { Backdrop } from "../../theme.slint";

// SidebarItem component bound to IconTextItem model element
export component SidebarItem inherits Rectangle {
    in property<IconTextItem> item;

    // Assigned index in the parent Sidebar
    in property<int> index;

    // Whether we emit clicks and look clickable
    in property<bool> interactive;

    in-out property<bool> selected: false;

    in-out property<brush> foreground: Palette.foreground;

    // Only emitted if the parent is interactive
    callback clicked();

    // Touch area for the item
    touch := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: root.interactive ? MouseCursor.pointer : MouseCursor.default;
        clicked() => {
            if (root.interactive) {
                root.clicked();
            }
        }
    }

    background: transparent;
    border-radius: 0px;

    states [
        active when root.selected: {
            background: Palette.selection-background.with-alpha(0.25);
            in {
                animate * {
                    duration: 0.2s;
                    easing: ease-in-out;
                }
            }
        }
    ]

    HorizontalLayout {
        spacing: 16px;
        padding-top: 12px;
        padding-bottom: 12px;
        padding-left: 32px;
        padding-right: 48px;
        alignment: start;

        VerticalLayout {
            alignment: center;
            padding: 0px;
            spacing: 0px;
            Image {
                source: item.icon;
                width: 24px;
                height: 24px;
            }
        }

        txt := Text {
            text: item.text;
            font-size: 18px;
            font-weight: 400;
            color: root.foreground;
        }
    }
}
